image: python:3.8-alpine

before_script:
  # rsync
  - 'command -v rsync >/dev/null || ( apk update && apk add rsync )'
  # ssh
  - 'command -v ssh-agent >/dev/null || ( apk update && apk add openssh-client )'
  - eval $(ssh-agent -s)
  #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  #- echo "${SSH_PRIVATE_KEY}" | base64 -d | ssh-add - >/dev/null
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  #- ssh-keyscan example.org >> ~/.ssh/known_hosts
  #- chmod 644 ~/.ssh/known_hosts
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  # python
  - apk add gcc musl-dev libc-dev linux-headers
  - pip3 install -r requirements.txt
    
deploy_dev:
  stage: deploy
  environment:
    name: dev
    url: doc-dev.biblissima.fr
  script:
    #- ssh root@example.com "cd var/www/ && git checkout master && git pull origin master && exit"
    #rsync -av --delete public/ root@example.org:www/
  only:
    - main
